### ISSUE TITLE
https://schemas.xmlsoap.org/soap/encoding/ 404 error

### ISSUE THREAD

**Issue by MMcintire96** [suds-community/suds#100]
When using Import and ImportDoctor to fix a broken schema, the auto import of "https://schemas.xmlsoap.org/soap/encoding/" is throwing a 404...

I'm pretty certain this is not an issue on this Repo's end, but I'm wondering if there is a workaround, or if anyone has the the encoding schema from "https://schemas.xmlsoap.org/soap/encoding/" downloaded.

**Comment by phillbaker** [comment]
Hi @MMcintire96, that doesn't sound like a bug with the library. Directly visiting that URL returns a 200 for me: https://schemas.xmlsoap.org/soap/encoding/. If you're looking for a cached version you can take a look at google's cache here: https://webcache.googleusercontent.com/search?q=cache:https://schemas.xmlsoap.org/soap/encoding/
