### ISSUE TITLE
Prefixes?

### ISSUE THREAD

**Issue by AfroCheremsha** [suds-community/suds#103]
Hi! I am creating a nested element with the prefix "ns4"
`
applicationWrapper = client.factory.create('ns0:ApplicationDataWrapper.applicationData')
applicationWrapper['ns4:GetVetDocumentByUuidRequest'] = vet
`
But if you look at the sent request, the prefix is completely different. And each time it changes to a random one.
"suds" itself understands all namespaces normally, but something incomprehensible is happening specifically in "GetVetDocumentByUuidRequest". Please explain why it works this way

`
print(client.last_sent()) >>>
 <ns1:data>
               <ns1:GetVetDocumentByUuidRequest>
                   ....
               </ns1:GetVetDocumentByUuidRequest>
            </ns1:data>
`

**Comment by AfroCheremsha** [comment]
Full.
`
wsdl_g2b = '---'

soap_login = '---'
soap_password = '---'
transport = HttpAuthenticated(username = soap_login, password = soap_password)  


client = Client(wsdl_g2b, transport = transport, faults = False)
apikey = client.factory.create('ns0:APIKey')
apikey = '---'

usr = client.factory.create('ns5:User')
usr.login = '---'

vet = client.factory.create('ns4:GetVetDocumentByUuidRequest')

vet.localTransactionId = '---'
vet.uuid = '---'
vet.enterpriseGuid = '---'
vet.initiator = usr

application = client.factory.create('ns0:Application')
applicationWrapper = client.factory.create('ns0:ApplicationDataWrapper.applicationData')
applicationWrapper['ns4:GetVetDocumentByUuidRequest'] = vet


application.serviceId = '---'
application.issuerId = '----'
application.issueDate = datetime.datetime.now().strftime("%Y-%m-%dT%H:%M:%S")
application.data = applicationWrapper
response = client.service.submitApplicationRequest(apiKey = apikey, application = application)
`

**Comment by phillbaker** [comment]
This issue tracker is for reporting bugs on the library, not user support. You may try posting this issue on a site like stackoverflow to get support. 

If you think this is a bug with the library, in order to investigate this further, we'll need the following:

* publicly available url for the wsdl in question
* runnable python code snippet
* package and version of suds being used

Note: if these can't be provided, we'll have to close this issue.
