### ISSUE TITLE
setuptools.command.test deprecated (is now a stub)

### ISSUE THREAD

**Issue by vishwin** [suds-community/suds#105]
https://github.com/suds-community/suds/blob/ff8a698af1255e176e4d7a740704d695b41655c8/setup.py#L411

package now fails to build because `setuptools.command.test` became a stub to serve as a softer but still forceful deprecation notice, see pypa/setuptools#4522 pypa/setuptools#4519 pypa/setuptools#4520

**Comment by phillbaker** [comment]
Thanks, reading those summaries, my understanding is that v72.0.0 of
setuptools is yanked and this package is installable with 72.1.0. The new
due date for removing is 15 Dec 2024, see pypa/setuptools#4522
<https://github.com/pypa/setuptools/pull/4522>. Given that, we should do
this, but it's not super urgent.

**Comment by vishwin** [comment]
The stub refers to 72.1.0.

**Comment by vishwin** [comment]
Still fails on 72.2.0.

**Comment by phillbaker** [comment]
Can you share the command you’re running that fails and the error?

**Comment by vishwin** [comment]
In this case `setup.py config`, but literally *any* `setup.py` invocation will fail in the same manner, simply because the referenced code exists.
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 509, in <module>
    from setuptools.command.test import (normalize_path as _normalize_path,
ImportError: cannot import name 'normalize_path' from 'setuptools.command.test' (/usr/local/lib/python3.11/site-packages/setuptools/command/test.py)
```
The entire testing "framework" in `setup.py` needs removed in order to fix this. pytest et al can and should be invoked outside of setuptools anyway.
