### ISSUE TITLE
http basic auth - 401 error - HttpTransport lost request.headers

### ISSUE THREAD

**Issue by guifran001** [suds-community/suds#11]
Originally from: https://bitbucket.org/jurko/suds/issues/135/http-basic-auth-401-error-httptransport
Pull request was already existing:  https://bitbucket.org/jurko/suds/pull-requests/43/httptransportopen-pass-request-headers-to

I will open a pr with the fix

**Comment by guifran001** [comment]
pr: https://github.com/suds-community/suds/pull/12

**Comment by phillbaker** [comment]
Closed in #12
