### ISSUE TITLE
Is suds-community currently compatible with suds-jurko?

### ISSUE THREAD

**Issue by aseques** [suds-community/suds#25]
Sorry if this can be found somewhere else, but I can't find it, I have a current setup working with suds-jurko, I would like to migrate it to a maintained fork. I have this code that has been working for a couple of years:
```
from suds import client
from suds.sudsobject import asdict
from suds import WebFault
```
But now I get an error when importing the class.
```
    from suds import client
ImportError: cannot import name 'client' from 'suds' (unknown location) 
```
Issue might be very basic but I haven't been able to fix it, also I was thinking that remove suds-jurko and adding instead suds-community would do the job.

**Comment by phillbaker** [comment]
@aseques are you using the last released version of suds-jurko or suds-jurko master?

**Comment by aseques** [comment]
just did 
> pip3 uninstall suds-jurko
> pip3 install suds-community  # (0.8.3)

**Comment by aseques** [comment]
Hi @phillbaker sorry for the delay, I just installed the code from git master (python setup.py install) instead of using the release from pip, and it works as expected, might it be something related to the bundle?

**Comment by phillbaker** [comment]
Very odd! Others and I don’t seem to have issues with the pip version.
Would you be able to uninstall and reinstall via pip and use the -v flag
when installing?

Also can you try importing via the python shell? (Any chance there’s an
issue with virtualenv or python version?)

**Comment by aseques** [comment]
@phillbaker I don't know what happened but after removing the install from src manually and installing again the pip version it kept working. I'm closing until it happens again and I can investigate more. Thanks for your help
