### ISSUE TITLE
Non-standard service name

### ISSUE THREAD

**Issue by MrLucio** [suds-community/suds#33]
Cannot call a service with non-standard service name (example: `client.service.wsExtAuth..ckAuth`).

Tried with [this](https://stackoverflow.com/questions/34539092/python-suds-client-and-not-standard-service-name) solution but got this error:

> SAXParseException: <unknown>:77:13: not well-formed (invalid token)

**Comment by phillbaker** [comment]
Can you provide a link to a wsdl that has this issue and/or write a failing
test case?

**Comment by MrLucio** [comment]
Thank you for helping me. I ended up not checking the issues anymore and I forgot it.
I really appreciate that.
