### ISSUE TITLE
README improvements / clarification

### ISSUE THREAD

**Issue by hansfn** [suds-community/suds#35]
Just some ideas:

- The descriptions says "A community fork of the jurko fork.". I can not see that this info is part of the README. IMHO I think you need to repeat it since the README should be self contained.
- Make it clear which Python versions are supported or at least which versions you try to support.
- Split the README in two files - a shorter README file with installation instructions and made an Hello World example and a longer USAGE file or DOCUMENTATION file with the rest of the info.
- I assume the sentence "This is hopefully just a temporary fork of the original suds Python library project created because the original project development seems to have stalled. Should be reintegrated back into the original project if it ever gets revived again." is coming from the jurko fork? However, the Fedora hosted version will never come back. And it might be read as you want this project reintegrated in the jurko fork. Maybe just delete it?

Thx for reading this far. If none of the above make sense to you, just close the issue.

**Comment by phillbaker** [comment]
These seem fine to me, except for (3). I'd like to keep everything in the README because it's prominent and easily editable. Please make a PR with the other suggestions!

**Comment by ovnicraft** [comment]
@hansfn i am agree  except for 3, for documentation we can follow the standard way.

Can you open the PR?

**Comment by ovnicraft** [comment]
@phillbaker from description on repo can you remove "jurko fork" ? 
At this time, git log is enough to read that :)

**Comment by phillbaker** [comment]
Fixed in 34171f0abe10a8c2a2acd9c43fb48bb02d25447b

**Comment by ovnicraft** [comment]
@phillbaker IMO

![image](https://user-images.githubusercontent.com/31282/81601359-593d8880-9390-11ea-80f6-f3b2b2c82284.png)

we can remove it from here too.
