### ISSUE TITLE
Create suds-community conda package on conda-forge

### ISSUE THREAD

**Issue by emiliom** [suds-community/suds#37]
I was very glad to discover `suds-community`, after using `suds-jurko` (and `suds` before that) for a few years and realizing that it's no longer maintained.

There's been a [suds-jurko conda package](https://anaconda.org/conda-forge/suds-jurko) on [conda-forge](https://conda-forge.org) for a long time, and it'd be great to have a `suds-community` package there as well. I can offer to help with this.

It's fairly easy to do this. See the [Getting started section](https://github.com/conda-forge/staged-recipes#getting-started) of the `conda-forge/staged-recipes` README file, possibly supplemented by the Step-by-step Instructions [here](https://conda-forge.org/docs/maintainer/adding_pkgs.html#step-by-step-instructions). To generate the content of the conda recipe `meta.yml` file, I recommend the [Grayskull online tool](https://www.marcelotrevisani.com/grayskull), which only needs the name of the pip package (it runs successfully with `suds-community`); you then only need to edit it by replacing `ADD_YOUR_GITHUB_ID_HERE` with the maintainer's github handle.

**Comment by phillbaker** [comment]
Hello! Hopefully suds-community will be useful. If I'm understanding correctly a separate repo would be created, for example, similar to https://github.com/conda-forge/suds-jurko-feedstock. Does that have to be the maintainer of the upstream repo? 

I unfortunately don't have time to maintain a downstream project currently, but it be great if you'd like to take this on.

**Comment by emiliom** [comment]
Right, a separate repo is needed, based on a fork of https://github.com/conda-forge/staged-recipes. The maintainer of that repo doesn't have to be the same as the maintainer of the upstream repo (`suds-community/suds`), though that would be ideal.

But I understand the concern about the time commitment. So, for now, I offer to take it on. I've gone ahead and created the repo, and edited the necessary [meta.yaml recipe](https://github.com/ulmo-dev/staged-recipes/blob/createrecipe/recipes/suds-community/meta.yaml). This was generated from the latest package on pypi.

If it's ok with you, I'm ready to move forward. The next step is submitting a PR to conda-forge. After that, I believe the next steps are largely automatic, unless problems come up. I can keep you posted.

**Comment by phillbaker** [comment]
Thanks! Looks great. 

I'll go ahead and close this out.
