### ISSUE TITLE
Upload source archive to PyPI

### ISSUE THREAD

**Issue by btb** [suds-community/suds#4]
The only wheel on pypi is for python 3, so soap-community can't be installed on 2.7. PyPI ought to at at least have the source archive (.tar.gz) which will make this possible.

**Comment by phillbaker** [comment]
Thanks @btb, good point!

I'll add this to travis, looks like some helpful links are:
* https://github.com/travis-ci/travis-ci/issues/8471
* https://docs.travis-ci.com/user/deployment/pypi/#uploading-different-distributions

**Comment by phillbaker** [comment]
Hi @btb looks like we got a universal wheel built and pushed to pypi: https://pypi.org/project/suds-community/#files. The travis hit a problem, it looks like on trying to push a `bz2`.

**Comment by btb** [comment]
I think there is a problem with the 0.7.1 universal wheel. My builds work in python 2.7, but not in 3.x:
https://travis-ci.org/uw-it-cte/uw-ems-client/builds/444769238

However my builds do work if I use the 0.7.0 wheel for 3.x and the 0.7.1 wheel for 2.7:
https://travis-ci.org/uw-it-cte/uw-ems-client/builds/445285559

They also all work if I install from source (github):
https://travis-ci.org/uw-it-cte/uw-ems-client/builds/444803058

I believe the root of the problem is that the suds build itself uses py2to3, so the generated packages for python 2 and 3 are different, and a universal wheel is not possible (The 0.7.1 wheel was generated in the travis build for 2.7, so it's really only compatible with 2.7).

**Comment by btb** [comment]
They appear to be working great, thanks
