### ISSUE TITLE
warnings when building docs in python3 compatibility

### ISSUE THREAD

**Issue by emezeta** [suds-community/suds#42]
If you are using Sphinix for python3.x when building the documentation, you will see a couple of warnings about syntax errors in suds' code.
If the purpose is to maintain 2.7 compatibility, some modifications are needed to ensure compatibility as well as to avoid such warnings. Otherwise it's just a matter of syntax. 
Whatever the case, I can take care of that.

***   File "./suds/xsd/query.py", line 57    
    raise Exception, 'not-implemented by subclass'
https://github.com/suds-community/suds/blob/6117f178227a650ce3f33932fe1640a83a4d39cd/suds/xsd/query.py#L57

and so on...    
***   File "./suds/xsd/sxbasic.py", line 671
    raise Exception, "%s mismatch" % TNS
 ***   File "./tests/external/axis1.py", line 171
    except WebFault, f:
 ***   File "./tests/external/jasper.py", line 38
    except WebFault, f:
 ***   File "./tests/external/public.py", line 65
    except WebFault, f:
 ***   File "./tests/external/rhq.py", line 109
    except WebFault, f:
 ***   File "./tests/external/saxenc.py", line 29
    print 'A(parsed)=\n%s' % a

**Comment by phillbaker** [comment]
Yes - readthedocs is building using python2.7: https://github.com/suds-community/suds/blob/master/.readthedocs.yml

**Comment by phillbaker** [comment]
May also be fixed by https://github.com/suds-community/suds/commit/83ae0c96b245aae97b842e75617eea6ad030eb50
