### ISSUE TITLE
gzip and deflate compression with headers 'Content-Encoding' and 'Accept-Encoding'

### ISSUE THREAD

**Issue by sebromon** [suds-community/suds#45]
Suds library does not take into account headers like 'Content-Encoding' and 'Accept-Encoding'

The following patch fixes the bug.

https://github.com/sebromon/suds/commit/ad12bc40e854674e02021a66617dfac00c7d0e75

With this commit :
 - Message is compressed if Content-Encoding is provided and equals to gzip or deflate.
 - Message is decompressed if Content-Encoding is present in response headers and equals to gzip or deflate.

But suds library should use urllib3 which compress or decompress data automatically.

This patch works in Python 3 with web-services SOAP with Apache server.

**Comment by phillbaker** [comment]
Moving this library to python3 and fully converting to python3 is a goal for this library, however, while we work to that end, would you like to submit that patch as a pull request?

**Comment by phillbaker** [comment]
I've cherry-picked your commit here: fb02619
