### ISSUE TITLE
Suds vs SoapClient

### ISSUE THREAD

**Issue by reisnobre** [suds-community/suds#47]
Hi, I'm having different results while creating a soap client and a suds client.

I don't understand a lot about soap, but I think both so should be the same right?

**Comment by phillbaker** [comment]
Are you referring to https://github.com/suds-community/suds/blob/60c407422223f84713a80913b2544fa35b78bf8f/suds/client.py#L628

That's an internal helper, that is separate from the public Suds client as described in the readme.

**Comment by phillbaker** [comment]
HI @reisnobre I'm going to close this issue for now, please re-open if you have further details.
