### ISSUE TITLE
Change the value of "elementFormDefault"

### ISSUE THREAD

**Issue by huseyin** [suds-community/suds#48]
Recently we needed to set the value of `elementFormDefault` from `qualified` to `unqualified` because of third-party requirements. However, I didn't find any related line about that after a quick look into your guide. Does anyone describe a possible solution?

**Comment by phillbaker** [comment]
Hi @huseyin if I'm understanding correctly, this change should be done in the upstream WSDL/XSD.

Otherwise, can you link (or provide if protected) the wsdl/xsd you're having issues with a code sample to reproduce the issue you're seeing?

**Comment by phillbaker** [comment]
Hi @huseyin without further details, I'm going to close this issue. Please reopen it if you can provide a working replication of the issue.
