### ISSUE TITLE
Add / link to Epydocs

### ISSUE THREAD

**Issue by phillbaker** [suds-community/suds#5]
Originally hosted at http://jortel.fedorapeople.org/suds/doc.

@emezeta has pulled these into a repo here: https://github.com/emezeta/doc_suds.

It'd be good to render and/or add to the build system to render them somewhere. Maybe https://readthedocs.org/?

**Comment by ovnicraft** [comment]
+1 for RTD

**Comment by Bobspadger** [comment]
I added them to the suds repo on bitbuket a while ago as well

https://bitbucket.org/jurko/suds/wiki/Home

**Comment by phillbaker** [comment]
Closing as a dupe of https://github.com/suds-community/suds/issues/36
