### ISSUE TITLE
Support for python 3.6+ planned?

### ISSUE THREAD

**Issue by cdvv7788** [suds-community/suds#52]
Currently in pypi only python up to 3.6 can use this package.

**Comment by phillbaker** [comment]
Hello, thanks for opening an issue. Can you be specific about the limitation you're seeing?

I see that we only list up to python 3.6 in the classifiers here: https://github.com/suds-community/suds/blob/14910001c2c782521d9ad8154aabfb0d06e67c0d/setup.py#L710-L712

However, that's not a hard requirement like [`python_requires`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires). In addition, python 3.6 through 3.9 are currently tested: https://github.com/suds-community/suds/blob/14910001c2c782521d9ad8154aabfb0d06e67c0d/.travis.yml#L6-L9

**Comment by cdvv7788** [comment]
My bad. Indeed it works. It would be nice to add the tags in `pypi` so 3.8 shows there too. Thanks for answering. Closing this.
