### ISSUE TITLE
 onvif 0.2.0 depends on suds>=0.4

### ISSUE THREAD

**Issue by dipcb05** [suds-community/suds#56]
I am trying to install onvif in my Django project. 
it depends on suds. 

i try to reinstall suds by pip, output - 
Requirement already satisfied: suds in /home/dip05/anaconda3/lib/python3.7/site-packages (0.3.5)

how I can I solve it, and upgrade

**Comment by dipcb05** [comment]
i also try to install onvif 0.4 using pip. 

error:

 pip install suds==0.4
Collecting suds==0.4
  Using cached suds-0.4.tar.gz (104 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/dip05/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py'"'"'; __file__='"'"'/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1gjn0vm8
         cwd: /tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/setup.py", line 20, in <module>
        import suds
      File "/tmp/pip-install-lsy9asid/suds_55a5bbb1e4954c50bf56df351e6e7092/suds/__init__.py", line 154, in <module>
        import client
    ModuleNotFoundError: No module named 'client'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/bc/d6/960acce47ee6f096345fe5a7d9be7708135fd1d0713571836f073efc7393/suds-0.4.tar.gz#sha256=d5524ae523bb9e09c57bcdbd1efae2c287d20603688ea31f6020ed180a489af0 (from https://pypi.org/simple/suds/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement suds==0.4 (from versions: 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.4)
ERROR: No matching distribution found for suds==0.4

**Comment by phillbaker** [comment]
Hello - if you're referring to the package here: https://github.com/quatanium/python-onvif/blob/09ffc65b8cd9d141b6a386804e7af7028755034e/setup.py#L8, then that uses the original `suds` project (https://pypi.org/project/suds/).

This project is `suds-community` (https://pypi.org/project/suds-community/). If you'd like the onvif project to switch dependencies, please open an issue on that repository.

I'm going to close this issue as it's not actionable for suds-community.
