### ISSUE TITLE
consider moving suds-community to jazzband

### ISSUE THREAD

**Issue by graingert** [suds-community/suds#59]
From the website (https://jazzband.co/):

> Jazzband is a collaborative community to share the responsibility of maintaining Python-based projects.
> 
> It gives maintainers and contributors the ability to “play in the same band” instead of being forced into “artist” and “audience” roles.
>
> When you join Jazzband you will become a member of its GitHub organization and granted a wide range of privileges there such as pushing code to repositories, triaging issues, merging pull requests, etc.
> 
> You can leave administrative tasks to the roadies, the people making sure the band can play when they want.
> Once you are a member you can transfer an existing repo to the Jazzband organization as long as you follow the guidelines. There are also many existing Jazzband projects which you can start contributing directly.

> When creating a new project or moving an existing one to the Jazzband there are some guidelines to follow. They exist to make sure that the Jazzband stays useful as a place to share responsibility for software maintenance when a number of projects are created at or moved to it.

Checklist:

- [x] Visibility: Established projects with a history of outside contributions that seek more maintainers are best suited for transfer to the Jazzband.
- [x] Documentation: Projects require prose documentation for end users and contributors. Inline code documentation is considered an indicator for a high quality of code and is also strongly recommended.
- [x] Tests: Projects must have tests that are easy to run. Automatic testing based on contributions (e.g. GitHub Actions) is also strongly encouraged. The test coverage requirement follows the “perfect is the enemy of the good” motto – it’s enough if the tests cover the core API of the project.
- [ ] Conduct: Projects are required to adopt and follow the Jazzband code of conduct. Please see the Contributor Code of Conduct for more information what that entails and how to report conduct violations.
- [ ] Contributing Guidelines: Projects have to add a CONTRIBUTING.md or CONTRIBUTING.rst file to their repository so it’s automatically displayed when new issues and pull requests are created.

**Comment by phillbaker** [comment]
I'm going to close this as there's been no response for almost a year. If the community is interested in contributing to suds, let's reopen and I'm happy to discuss.
