### ISSUE TITLE
Rename Python Package to suds 

### ISSUE THREAD

**Issue by ovnicraft** [suds-community/suds#6]
Package still suds-jurko, could be better if its renamed to suds, this result on:
`pip install suds`

i ran `pip search suds` and got this result: 

https://gist.github.com/ovnicraft/98e5f90fe9e054d34f7b4f137b70f755

Possible nice to have

**Comment by phillbaker** [comment]
This package is `suds-community` (on pypi: https://pypi.org/project/suds-community/), but updating it would be great. Looks like I did miss one `suds-jurko` in the readme: https://github.com/suds-community/suds#installation.

@jortel looks like you have your own fork on github as well: https://github.com/jortel/suds, any thoughts here?

**Comment by jortel** [comment]
@phillbaker, Not exactly sure what you're asking.  The https://github.com/jortel/suds repository and `suds` package in pypi are the original `suds` project (not forks).

**Comment by ovnicraft** [comment]
> This package is `suds-community` (on pypi: https://pypi.org/project/suds-community/), but updating it would be great. Looks like I did miss one `suds-jurko` in the readme: https://github.com/suds-community/suds#installation.

I updated the README :-)
> 
> @jortel looks like you have your own fork on github as well: https://github.com/jortel/suds, any thoughts here?

**Comment by phillbaker** [comment]
Great, good to close @ovnicraft ?

**Comment by phillbaker** [comment]
@jortel sorry to ping on this old issue, but would you be open to this project releasing updated versions of the original `suds` package on pypi? (Ie transferring ownership?)

With python 2 no longer supported and forks multiplying, it'd be great to get the original package updated to reduce the duplicate maintenance work we're seeing.
