### ISSUE TITLE
Does suds support this security implementation?

### ISSUE THREAD

**Issue by conradogarciaberrotaran** [suds-community/suds#66]
Hi, i'm trying to send message to a SOAP server with some confusing security layer and I want to see if SUDS has the way to implement this:
I've been provided with some public and private keys, a certificate and a JKS file.
I have the instructions to make it work in SOAPUI, apparently I need to encrypt the body of the message with this settings:
![image](https://user-images.githubusercontent.com/29988404/146403014-35847e95-f5b1-4725-9d9d-8c1c070e1f98.png)
And also add a SHA1 signature
![image](https://user-images.githubusercontent.com/29988404/146403064-adebdaf3-34ef-42ac-b0b7-104ea343d10b.png)
Along side a timestamp element.

Can SUDS make this work? any help is greatly appreciated.

**Comment by phillbaker** [comment]
Hello, I see you also asked a similar question on the [zeep repo](https://github.com/mvantellingen/python-zeep/issues/1281). Unfortunately, contributors not able to provide support for using suds. Please refer to the available documentation and let us know how your project goes.

If you determine that there are specific features or bugs you encounter while working on this, please open a specific issue for that. This issue will be closed in a few days unless more information is provided.

**Comment by phillbaker** [comment]
I'm going to close this issue for now. please reopen it if there are specific bugs or a feature request.
