### ISSUE TITLE
pypi suds vs suds-community

### ISSUE THREAD

**Issue by zenoran** [suds-community/suds#77]
Sorry for my ignorance, but I'm having difficulty understanding which version is which.  The documentation claims they are the same, yet the pypi versions are different for each.  I also noticed they both link back to the same github repo so it's a little unclear why suds-community has a later release published on pypi?  Which is the correct package name for importing?

**Comment by phillbaker** [comment]
Whoops, sorry about the confusion, they are the same package. I missed the automatic deployment to `suds` in CD. That's been fixed with 76b0533d475f47a88983370094a64b1443e396cf.

New versions are now being pushed to both locations.
