### ISSUE TITLE
Replacing `suds-jutrko` with `suds-community`

### ISSUE THREAD

**Issue by John15321** [suds-community/suds#81]
At work we have quite a lot of old projects that use `suds-jurko` and as we all know its outdated and dead. Im looking into replacing it with `suds-community`. And my hope is that it is somehow 1to1 mapping of the `suds-jutrko` interface?

How hard would it be to change out jurko for community?

**Comment by phillbaker** [comment]
Hello, suds-community is a continuation of the suds-jurko codebase. We've avoided making breaking changes. 

A few things to be aware of:
* https://github.com/suds-community/suds/commit/366f7f1616595b9e4163a3f90fc6e84ac0ae23f5 has an update to the readme, https://github.com/suds-community/suds#initializing-optional-arrays-with-lists on a behavior, about some behavior regarding initializing optional arrays. Please see https://github.com/suds-community/suds/issues/67#issuecomment-1030960131 and https://github.com/suds-community/suds/issues/14 for more
* last_received was just restored (removed in the jurko fork): https://github.com/suds-community/suds/issues/79

It _should_ be a drop in replacement, however it's always good to test

**Comment by phillbaker** [comment]
Closing this issue, please reopen if further questions come up
