### ISSUE TITLE
nusoap_client parameter

### ISSUE THREAD

**Issue by alirezamosleh** [suds-community/suds#83]
We want to rewrite this nusoap_client request on suds:
`$client = new nusoap_client('https://appketaba.com/Webservice/index.php?wsdl', 'wsdl',
$proxyhost, $proxyport, $proxyusername, $proxypassword);`
the problem is suds doesn't accept these parameters
how to handle it؟

**Comment by phillbaker** [comment]
Hello, if your question is about using proxies with Suds, please see the documentation: https://github.com/suds-community/suds#proxies

It looks like you're comparing suds to a PHP package. Contributors to suds are not generally able to provide support for using suds, other support oriented sites like stackoverflow may be able to help and contain answers to common questions. If you determine that there are specific features or bugs you encounter while working on this, please let us know.

**Comment by phillbaker** [comment]
Closing this issue as there have been no follow ups.
