### ISSUE TITLE
Initialize an object without any attribute

### ISSUE THREAD

**Issue by sunyingji** [suds-community/suds#85]
My suds version is 0.6.

[root@compute-c05c9c49-c21986-compute-0 suds]# pip list |grep suds
suds-jurko             0.6

I have an VirtualMachineBootOptionsBootableDevice definition like below. There is not any attribute defined in it.

<complexType xmlns="http://www.w3.org/2001/XMLSchema" xmlns:vim25="urn:vim25" name="VirtualMachineBootOptionsBootableDevice">
            <complexContent>
               <extension base="vim25:DynamicData">
                  <sequence>
                  </sequence>
               </extension>
            </complexContent>
         </complexType>

and a BootOptions object defined as below

<complexType xmlns="http://www.w3.org/2001/XMLSchema" xmlns:vim25="urn:vim25" name="VirtualMachineBootOptions">
            <complexContent>
               <extension base="vim25:DynamicData">
                  <sequence>
                     <element name="bootDelay" type="xsd:long" minOccurs="0"/>
                     <element name="enterBIOSSetup" type="xsd:boolean" minOccurs="0"/>
                     <element name="efiSecureBootEnabled" type="xsd:boolean" minOccurs="0"/>
                     <element name="bootRetryEnabled" type="xsd:boolean" minOccurs="0"/>
                     <element name="bootRetryDelay" type="xsd:long" minOccurs="0"/>
                     <element name="bootOrder" type="vim25:VirtualMachineBootOptionsBootableDevice" minOccurs="0" maxOccurs="unbounded"/>
                     <element name="networkBootProtocol" type="xsd:string" minOccurs="0"/>
                  </sequence>
               </extension>
            </complexContent>
         </complexType>

When I want to create BootOptions object with a BootableDevice in bootOrder, I always fail to do that. Each time client_factory.create('ns0:VirtualMachineBootOptionsBootableDevice') returns an <empty> for me. 

   bootOptions = 
      (VirtualMachineBootOptions){
         bootDelay = 0
         enterBIOSSetup = False
         efiSecureBootEnabled = False
         bootRetryEnabled = False
         bootRetryDelay = 20000
         bootOrder[] =
            <empty>,
         networkBootProtocol = "ipv4"
      }

However I need a BootableDevice to put in the array of BootableDevice.  My expectation is as below.
-->    bootOptions = (vim.vm.BootOptions) {
-->       bootDelay = 0, 
-->       enterBIOSSetup = false, 
-->       efiSecureBootEnabled = false, 
-->       bootRetryEnabled = false, 
-->       bootRetryDelay = 10000, 
-->       bootOrder = (vim.vm.BootOptions.BootableDevice) [
-->          (vim.vm.BootOptions.BootableDevice) {
-->          }
-->       ], 
-->       networkBootProtocol = ""
-->    }, 

Would you please help me on this issue ?

Yingji

**Comment by phillbaker** [comment]
> My suds version is 0.6.
> [root@compute-c05c9c49-c21986-compute-0 suds]# pip list |grep suds
> suds-jurko 0.6

suds-jurko is a different and no longer maintained project. Issues on this repository are for reporting bugs and feature requests for this provider, not providing support for unique environments. In order to investigate this, a reproducible case may needs to be provided, if that can't be provided, we'll have to close this issue to focus on widely impacting issues.
