### ISSUE TITLE
Convert suds object to dict

### ISSUE THREAD

**Issue by ron819** [suds-community/suds#9]
One of the things missing in suds but exists in zeep (zeep.helpers) is the ability to convert object (suds object) into something that the user can parse like dict or json.

Related stack-overflow:
https://stackoverflow.com/questions/2412486/serializing-a-suds-object-in-python

It will be great if this lib can support this needed feature like zeep does.

**Comment by phillbaker** [comment]
Thanks for opening an issue! Any interest in PRing one of the suggestions
in the SO post?

**Comment by phillbaker** [comment]
Just noting that there is:

https://github.com/suds-community/suds/blob/0f18b272d0702b7253b5b8beedacd53c8d63ab65/suds/client.py#L79-L89

which should be available as:
```
from suds import Client
Client.dict(suds_object)
```

**Comment by aseques** [comment]
I'd would be interested in this too, currently I am using a function to do this conversion.

**Comment by phillbaker** [comment]
@aseques thanks! So that I'm clear - how is the function you're using different than `Client.dict(suds_object)`?

**Comment by aseques** [comment]
I am checking right now, i opened another issue because I haven't been able to use suds community at the moment

**Comment by johnziebro** [comment]
I came across this issue looking at how to serialize Suds results to replace Zeep's helper capability to do so. I reviewed [SO: serializing-a-suds-object-in-python](https://stackoverflow.com/questions/2412486/serializing-a-suds-object-in-python) and the Suds Client.dict() classmethod.

The initial difference I see is that the Client.dict() classmethod is not recursive, while the SO answer is.

When dealing with an array of Suds objects, I've found that the SO answer will produce a dictionary containing a single key named items whose value is a list of dicts.
`{ "items": [{"field_a", "field_b, ...}, {"field_a", "field_b, ...}]`

This structure seems superfluous, where you would just want to have a list of Suds objects serialized to dicts returned.
`[{"field_a", "field_b, ...}, {"field_a", "field_b, ...}]`

So this is the modified SO answer that also cleans up responses that might become serialized with a single key 'items' containing a list:
```python
    @staticmethod
    def _serialize(d, clean: bool = True):
        """ Serializes Suds objects recursively

        Usage:
        result = self.soap_client.service.getPeople()
        result = self._serialize(result)
        > [
        >   {"first_name": "John", "last_name": "Doe"},
        >   {"first_name": "Jane", "last_name": "Doe"},
        > ]

        Parameters:
        :param d: The result of a Suds query of an endpoint possibly containing Suds
            objects to be serialized.
        :param clean: bool: Flag to surface the value of key; 'items' when 'items' is the 
            only key resulting dict.
        :return: Any: A Pythonic json-like serialized structure.
        """

        def recursive_asdict(d):
            """Convert Suds object into serializable format."""
            out = {}
            for k, v in asdict(d).items():
                if hasattr(v, '__keylist__'):
                    out[k] = recursive_asdict(v)
                elif isinstance(v, list):
                    out[k] = []
                    for item in v:
                        if hasattr(item, '__keylist__'):
                            out[k].append(recursive_asdict(item))
                        else:
                            out[k].append(item)
                else:
                    out[k] = v
            return out

        # recursively serialize the suds object
        serialized = recursive_asdict(d)

        if clean:
            if (len(serialized) == 1) and isinstance(serialized.get("item"), list):
                serialized = serialized.get("item")

        return serialized
```
I will circle back on this at a later point and see if I can PR a similar simpler version utilizing Client.dict recursively.
