### ISSUE TITLE
Suds makes underscores in front of parsed fields

### ISSUE THREAD

**Issue by aleksejs-fomins** [suds-community/suds#98]
Dear Suds developers,

Project I am working with a legacy code that is using a slightly older version `suds-py3>=1.4.1`, I am planning to migrate it to the current version soon.

The project uses WSDL read queries to a SOAP API in our organization. 

I am encountering a behaviour where some of the fields, that appear in the raw XML as "id" and "project" to appear in the non-raw response (i.e. XMLResponse) as "_id" and "_project". Why is this happening? Is there a way to switch this behaviour off? Is this still the case in the current version?

I am happy to provide any details you require on request.

**Comment by phillbaker** [comment]
Hello - please confirm what version of suds you're seeing this issue in? Please also provide a wsdl that reproduces this.

**Comment by aleksejs-fomins** [comment]
Hi. `suds.__version__` says '1.4.5.0'
The WSDL is
https://fgcz-bfabric-test.uzh.ch/bfabric/user?wsdl

I expect that you would not be able to make queries without a username and a password, which I don't have permissions to share.

**Comment by phillbaker** [comment]
> suds.__version__ says '1.4.5.0'

That's not a version released by this library. suds-py3 is a separate fork and bugs in suds-py3 could not be addressed here.

If you're using this package and seeing this error, please share the version of this library in which you're seeing the issue you describe.

**Comment by aleksejs-fomins** [comment]
Sorry, I will send the bug to suds-py3
